name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  carousel_slider: ^4.2.1
  webview_flutter: ^4.4.1
  flutter_html: ^3.0.0-beta.2
  # EasyRefresh：https://pub.dev/packages/easy_refresh
  easy_refresh: ^3.3.1
  get: ^4.6.6
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  video_player: ^2.8.6
  flutter_svg: ^2.0.10+1
  material_color_utilities: ^0.8.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/grade.json
   - assets/image/
